### ISSUE TITLE
db.dat is absent

### ISSUE THREAD

**Issue by AlexOUKS** [regulaforensics/react-native-document-reader#1]
Hi, I upgraded Regula from 5.0 to 5.2, updated the db.dat into the folder of the license and I have this message that db.dat is absent on the initializeReader error method.

Is there something I am missing?

**Comment by vyakimchik** [comment]
Hello. Please make sure that you use the latest database. Also, try to invoke the `removeDatabase` method before initialization if you install the app over the existing one.

Link to the docs: https://docs.regulaforensics.com/react-native/database#removing-database-using-removedatabase-method.

**Comment by AlexOUKS** [comment]
Hello Vladislav,

Thank you it works well !!
