### ISSUE TITLE
Unable to Install Pod's

### ISSUE THREAD

**Issue by UsamaIkraam0099** [regulaforensics/react-native-document-reader#14]
**Bug Description**
I try to integrate regula React-Native SDK into my app. After installing two dependencies "@regulaforensics/react-native-document-reader-api": "^6.4.0" AND "@regulaforensics/react-native-document-reader-core-doctype": "^6.4.0" I move to ios folder and type "pod install" but its not working. I mention the image below.

**Steps To Reproduce**

1. Go to project folder.
2. Install mention dependencies
3. Go to IOS folder and install "pod install"
4. Throwing error like 
[!] CocoaPods could not find compatible versions for pod "DocumentReader":
  In Podfile:
    RNDocumentReaderApi (from `../node_modules/@regulaforensics/react-native-document-reader-api`) was resolved to 6.4.0, which depends on
      DocumentReader (= 6.4.2552)

None of your spec sources contain a spec satisfying the dependency: `DocumentReader (= 6.4.2552)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Expected behavior**
It should be install without error.

**Screenshots**
![Screenshot 2022-07-20 at 9 54 05 AM](https://user-images.githubusercontent.com/77922449/179908785-c335d3c4-6450-490d-9ec4-36546f2bd6e1.png)

**Environment:**
 - Device: iPhone 12
 - OS: iOS
 - OS version: 14.4

**Comment by UsamaIkraam0099** [comment]
I'm using 30 days trial license. Any help would be appreciated, Thanks.

**Comment by vyakimchik** [comment]
Hi @UsamaIkraam0099,

Please try to run `pod update` instead of `pod install`. It seems that you don't have the required version of the Document Reader installed on your computer. If it doesn't help, try to execute the `pod repo update` command. Then let us know if it helps you.

**Comment by UsamaIkraam0099** [comment]
Hi **@vyakimchik**

Thanks for your help. I try with ### pod update and it works fine.
