### ISSUE TITLE
Duplicate Class Error in Android

### ISSUE THREAD

**Issue by UsamaIkraam0099** [regulaforensics/react-native-document-reader#15]
**Bug Description**
Duplicate Class Error in Android After installing "@regulaforensics/react-native-document-reader-core-ocrandmrz": "^6.4.0" in React Native

**Steps To Reproduce**

**Expected behavior**
It should be work perfictely

**Screenshots**
![Screenshot 2022-07-25 at 4 58 37 PM](https://user-images.githubusercontent.com/77922449/180783707-72250091-c1ec-483d-b860-13c923e2fb21.png)

**Environment:**
 - Device: Android Physical Device (LG G6).
 - OS: Android
 - OS version: Android 8

**Additional context**
Im using "@regulaforensics/react-native-document-reader-core-doctype": "^6.4.0" for passport scanning and its working fine but I also need to scan credit card so I go with "@regulaforensics/react-native-document-reader-core-ocrandmrz": "^6.4.0" so after installing this dependency Im not able to run the android project again.

**Comment by UsamaIkraam0099** [comment]
@PavelMasuk @DmitrySmolyakov 

Above I mention the screenshot of error. Any kind of help would be appreciated.

Thanks,

**Comment by vyakimchik** [comment]
Hello,

Thanks for reaching out to us!

It seems that you've added the `ocrandmrz` plugin in addition to the `doctype` one. This is not the correct way - you need to remove the `doctype` plugin, and use only `ocrandmrz` - it already contains the `doctype` Core functionality.

Please let us know when you try this suggestion.

**Comment by UsamaIkraam0099** [comment]
Hi @vyakimchik 

Yes, your suggestion works. Thanks for you response
