### ISSUE TITLE
"db.dat is incorrect"

### ISSUE THREAD

**Issue by Sandeep040593S** [regulaforensics/react-native-document-reader#2]
Failed during initialisation and throws below error
"Init failed:com.regula.documentreader.api.errors.DocReaderStateException: db.dat is incorrect"

**Comment by vyakimchik** [comment]
Hello. It seems that you use a database that is incompatible with the latest SDK. Try to update the database to the latest version.

**Comment by Sandeep040593S** [comment]
> Hello. It seems that you use a database that is incompatible with the latest SDK. Try to update the database to the latest version.

hey have used the same db which was shared to me by your team for a specific region
the same db works on Native android side

**Comment by Sandeep040593S** [comment]
> Hello. It seems that you use a database that is incompatible with the latest SDK. Try to update the database to the latest version.

Below is the version used 
API (Beta)

implementation('com.regula.documentreader:api:5.2.3076') {
        transitive = true
    }

**Comment by Sandeep040593S** [comment]
> Hello. It seems that you use a database that is incompatible with the latest SDK. Try to update the database to the latest version.

Have updated database to latest version but still no luck....shows the same error
"Init failed:com.regula.documentreader.api.errors.DocReaderStateException: db.dat is incorrect"

**Comment by vyakimchik** [comment]
Did you install the app with the new database over the existing one? If so, did you increase the app version (version code)? Also, try to invoke the following method before initialization: [`removeDatabase`](https://docs.regulaforensics.com/react-native/database#removing-database-using-removedatabase-method).

**Comment by vyakimchik** [comment]
The issue has been resolved which we were informed about.
