### ISSUE TITLE
demo license not working

### ISSUE THREAD

**Issue by gwomack** [regulaforensics/react-native-document-reader#4]
hello,

i created a demo license normally but for com.regula.documentreader package name

creating a license for com.regula.dr.fullrfid is not possible, it causes an error in the licensing generator form: Errors: Demo license for the product (Mobile Full SDK) and the application id (com.regula.dr.fullrfid) already exists

when running the app on my android i get an error:
[Mon Mar 29 2021 14:41:59.560]  LOG      Init failed:com.regula.documentreader.api.errors.DocumentReaderException: License step 5 fails: invalid system (1) or appID (com.regula.dr.fullrfid)

license file was successfully put on right folder
![image](https://user-images.githubusercontent.com/9201361/112879819-0a7c0880-90a0-11eb-8a91-622b58ca9b6c.png)

how can i license my demo app ?

**Comment by ikliashchou** [comment]
Hello,

Change appID to com.regula.documentreader?

**Comment by gwomack** [comment]
thanks for fast reply

where is appID located? im still learning react-native
is it on AndroidManifest.xml ?

**Comment by ikliashchou** [comment]
You may search in repo for "com.regula.dr.fullrfid" and replace it with "com.regula.documentreader" everywhere.

We will make it default appID, thanks for pointing this out. @PavelMasuk please make changes

**Comment by ikliashchou** [comment]
Or better get a demo license for your own appID and replace default one with it.

**Comment by vyakimchik** [comment]
Hi @gwomack,

Have you managed to run our demo project?

**Comment by vyakimchik** [comment]
@gwomack,

I close this issue due to inactivity for a long time. If you are still experiencing this issue, feel free to reopen it or create a new one.

Thanks!
